import { sitemapIndex } from '@dhakalive/core'
import { getLogger } from '@dhakalive/observability'
import { NextResponse } from 'next/server'

import { env } from '../../lib/env'
import { absoluteUrl } from '../../lib/routes'
import { countArticleSitemaps } from '../../lib/seo/sitemap-data'
import { getSeoDefaults } from '../../lib/queries/globals'
import { DEFAULT_LOCALE } from '@dhakalive/config'

/**
 * Sitemap index.
 *
 * The entry point search engines are given, and the only sitemap URL that ever
 * needs to be stable. Everything else is reachable from here, so adding or
 * re-chunking sitemaps never requires resubmitting anything.
 *
 * Hand-built rather than using Next's `sitemap.ts` convention: the news sitemap
 * needs the `news:` namespace, which `MetadataRoute.Sitemap` cannot express, and
 * having one sitemap generated by a different mechanism from the rest is worse
 * than generating all of them the same way.
 */
export const revalidate = 600

/** Shared by every sitemap route, so caching behaviour cannot drift between them. */
export const SITEMAP_HEADERS = {
  'content-type': 'application/xml; charset=utf-8',
  // Short at the edge, longer for a shared cache: crawlers refetch sitemaps
  // often and the cost of serving a ten-minute-old one is a ten-minute delay in
  // discovery, not an error.
  'cache-control': 'public, max-age=600, s-maxage=600, stale-while-revalidate=3600',
} as const

export async function GET(): Promise<NextResponse> {
  const siteUrl = env().NEXT_PUBLIC_SITE_URL

  /**
   * A site that has asked not to be indexed publishes no sitemap. Serving one
   * from staging is how a staging domain ends up in search results even with
   * `noindex` on every page — the sitemap is an invitation, and crawlers act on
   * it before they read the pages.
   */
  const defaults = await getSeoDefaults(DEFAULT_LOCALE)
  if (defaults.allowIndexing === false) {
    return new NextResponse('Not found', { status: 404, headers: { 'cache-control': 'no-store' } })
  }

  try {
    const chunks = await countArticleSitemaps()

    const entries = [
      { loc: absoluteUrl('/sitemaps/news.xml', siteUrl) },
      { loc: absoluteUrl('/sitemaps/taxonomy.xml', siteUrl) },
      ...Array.from({ length: chunks }, (_entry, index) => ({
        loc: absoluteUrl(`/sitemaps/articles-${index + 1}.xml`, siteUrl),
      })),
    ]

    return new NextResponse(sitemapIndex(entries), { headers: SITEMAP_HEADERS })
  } catch (error) {
    /**
     * A 500 here teaches a crawler the sitemap is unreliable and it backs off.
     * An empty-but-valid index is the better failure: it says "nothing to
     * report right now" and is retried on the normal schedule.
     */
    getLogger().error({ err: error }, 'Sitemap index generation failed')
    return new NextResponse(sitemapIndex([]), { headers: SITEMAP_HEADERS })
  }
}
