/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    articles: Article;
    categories: Category;
    tags: Tag;
    authors: Author;
    media: Media;
    'live-blogs': LiveBlog;
    'live-blog-updates': LiveBlogUpdate;
    pages: Page;
    users: User;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'live-blogs': LiveBlogsSelect<false> | LiveBlogsSelect<true>;
    'live-blog-updates': LiveBlogUpdatesSelect<false> | LiveBlogUpdatesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('bn' | 'en') | ('bn' | 'en')[];
  globals: {
    homepage: Homepage;
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
    'seo-defaults': SeoDefault;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'seo-defaults': SeoDefaultsSelect<false> | SeoDefaultsSelect<true>;
  };
  locale: 'bn' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'publish-scheduled': TaskPublishScheduled;
      'expire-breaking': TaskExpireBreaking;
      revalidate: TaskRevalidate;
      'search-index': TaskSearchIndex;
      'prune-jobs': TaskPruneJobs;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  headline: string;
  subheadline?: string | null;
  /**
   * URL segment. Leave blank to generate it from the title. Bengali characters are preserved.
   */
  slug: string;
  /**
   * Used in listings, social cards and search results.
   */
  summary?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Bylines, in the order they should appear.
   */
  authors?: (number | Author)[] | null;
  /**
   * Determines the article URL and its position in navigation.
   */
  primaryCategory?: (number | null) | Category;
  /**
   * Additional sections this story belongs to.
   */
  categories?: (number | Category)[] | null;
  tags?: (number | Tag)[] | null;
  /**
   * Required to publish, and it must already have alt text.
   */
  featuredImage?: (number | null) | Media;
  articleType:
    | 'standard'
    | 'breaking-news'
    | 'opinion'
    | 'editorial'
    | 'feature'
    | 'interview'
    | 'analysis'
    | 'photo-story'
    | 'video-story'
    | 'live-blog';
  /**
   * Only transitions allowed by your role are accepted.
   */
  workflowStatus:
    | 'draft'
    | 'submitted'
    | 'in-review'
    | 'changes-requested'
    | 'approved'
    | 'scheduled'
    | 'published'
    | 'unpublished'
    | 'archived';
  /**
   * Reason for this status change, e.g. what needs fixing. Recorded against the transition.
   */
  workflowNote?: string | null;
  /**
   * Every status change, who made it and when.
   */
  workflowHistory?:
    | {
        from?: string | null;
        to?: string | null;
        at?: string | null;
        actor?: (number | null) | User;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Set automatically on first publication.
   */
  publishedAt?: string | null;
  /**
   * When a scheduled article should go live. Published by the background worker.
   */
  scheduledAt?: string | null;
  /**
   * Shows in the breaking-news ticker.
   */
  isBreaking?: boolean | null;
  /**
   * When the breaking flag expires. Cleared by the worker.
   */
  breakingUntil?: string | null;
  isFeatured?: boolean | null;
  /**
   * Links this story to the same story written separately in another language. Leave empty when both languages live in this document as translated fields.
   */
  translationOf?: (number | null) | Article;
  correction?: {
    hasCorrection?: boolean | null;
    /**
     * Shown to readers on the article. Say what was wrong and what changed.
     */
    note?: string | null;
    correctedAt?: string | null;
  };
  createdBy?: (number | null) | User;
  lastEditedBy?: (number | null) | User;
  /**
   * Leave blank to derive metadata from the content itself.
   */
  seo?: {
    /**
     * Overrides the page title. Around 60 characters renders best.
     */
    title?: string | null;
    /**
     * Overrides the meta description. Around 155 characters.
     */
    description?: string | null;
    /**
     * Overrides the Open Graph image. Falls back to the featured image.
     */
    image?: (number | null) | Media;
    /**
     * Absolute URL. Set this only when this page is a duplicate of a canonical page elsewhere.
     */
    canonicalUrl?: string | null;
    /**
     * Ask search engines not to index this page.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  /**
   * The byline as it appears on the story.
   */
  displayName: string;
  /**
   * URL segment. Leave blank to generate it from the title. Bengali characters are preserved.
   */
  slug: string;
  /**
   * Links this public profile to a CMS account. Only administrators can set this.
   */
  user?: (number | null) | User;
  avatar?: (number | null) | Media;
  /**
   * e.g. Senior Correspondent, Dhaka
   */
  designation?: string | null;
  biography?: string | null;
  /**
   * Shown on the public profile. Leave blank to hide a link.
   */
  contact?: {
    email?: string | null;
    website?: string | null;
    x?: string | null;
    facebook?: string | null;
    linkedin?: string | null;
  };
  /**
   * Inactive authors keep their existing bylines but are hidden from author listings.
   */
  isActive?: boolean | null;
  /**
   * Leave blank to derive metadata from the content itself.
   */
  seo?: {
    /**
     * Overrides the page title. Around 60 characters renders best.
     */
    title?: string | null;
    /**
     * Overrides the meta description. Around 155 characters.
     */
    description?: string | null;
    /**
     * Overrides the Open Graph image. Falls back to the featured image.
     */
    image?: (number | null) | Media;
    /**
     * Absolute URL. Set this only when this page is a duplicate of a canonical page elsewhere.
     */
    canonicalUrl?: string | null;
    /**
     * Ask search engines not to index this page.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Internal display name, shown in the CMS.
   */
  name: string;
  /**
   * Roles grant capabilities. You cannot assign a role at or above your own level, and you cannot change your own roles.
   */
  roles?: ('contributor' | 'reporter' | 'editor' | 'publisher' | 'admin' | 'super-admin')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Images, video and documents. Alt text is required for images.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describes the image for screen readers. Required for images; an image cannot be used as a featured image without it.
   */
  alt?: string | null;
  /**
   * Shown beneath the image on the public site.
   */
  caption?: string | null;
  /**
   * Photographer or agency, e.g. "Reuters / Jane Doe".
   */
  credit?: string | null;
  copyright?: string | null;
  /**
   * Where the file came from — wire service, contributor, archive.
   */
  source?: string | null;
  /**
   * Derived from the file on upload; override if needed.
   */
  mediaType?: ('image' | 'video' | 'audio' | 'document') | null;
  /**
   * Shown to editors before they place the asset in a story.
   */
  usageRestrictions?: ('none' | 'editorial-only' | 'one-time' | 'internal') | null;
  uploadedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Section name as readers see it, e.g. রাজনীতি / Politics.
   */
  title: string;
  /**
   * URL segment. Leave blank to generate it from the title. Bengali characters are preserved.
   */
  slug: string;
  description?: string | null;
  /**
   * Leave empty for a top-level section. Maximum 4 levels.
   */
  parent?: (number | null) | Category;
  image?: (number | null) | Media;
  /**
   * Lower numbers appear first in navigation.
   */
  displayOrder?: number | null;
  /**
   * Inactive sections stay published but disappear from navigation.
   */
  isActive?: boolean | null;
  /**
   * Leave blank to derive metadata from the content itself.
   */
  seo?: {
    /**
     * Overrides the page title. Around 60 characters renders best.
     */
    title?: string | null;
    /**
     * Overrides the meta description. Around 155 characters.
     */
    description?: string | null;
    /**
     * Overrides the Open Graph image. Falls back to the featured image.
     */
    image?: (number | null) | Media;
    /**
     * Absolute URL. Set this only when this page is a duplicate of a canonical page elsewhere.
     */
    canonicalUrl?: string | null;
    /**
     * Ask search engines not to index this page.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  title: string;
  /**
   * URL segment. Leave blank to generate it from the title. Bengali characters are preserved.
   */
  slug: string;
  description?: string | null;
  /**
   * Leave blank to derive metadata from the content itself.
   */
  seo?: {
    /**
     * Overrides the page title. Around 60 characters renders best.
     */
    title?: string | null;
    /**
     * Overrides the meta description. Around 155 characters.
     */
    description?: string | null;
    /**
     * Overrides the Open Graph image. Falls back to the featured image.
     */
    image?: (number | null) | Media;
    /**
     * Absolute URL. Set this only when this page is a duplicate of a canonical page elsewhere.
     */
    canonicalUrl?: string | null;
    /**
     * Ask search engines not to index this page.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-blogs".
 */
export interface LiveBlog {
  id: number;
  title: string;
  /**
   * URL segment. Leave blank to generate it from the title. Bengali characters are preserved.
   */
  slug: string;
  summary?: string | null;
  status: 'draft' | 'live' | 'paused' | 'ended' | 'archived';
  authors?: (number | Author)[] | null;
  /**
   * The main story this coverage accompanies.
   */
  relatedArticle?: (number | null) | Article;
  startedAt?: string | null;
  endedAt?: string | null;
  createdBy?: (number | null) | User;
  /**
   * Leave blank to derive metadata from the content itself.
   */
  seo?: {
    /**
     * Overrides the page title. Around 60 characters renders best.
     */
    title?: string | null;
    /**
     * Overrides the meta description. Around 155 characters.
     */
    description?: string | null;
    /**
     * Overrides the Open Graph image. Falls back to the featured image.
     */
    image?: (number | null) | Media;
    /**
     * Absolute URL. Set this only when this page is a duplicate of a canonical page elsewhere.
     */
    canonicalUrl?: string | null;
    /**
     * Ask search engines not to index this page.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-blog-updates".
 */
export interface LiveBlogUpdate {
  id: number;
  liveBlog: number | LiveBlog;
  /**
   * Timestamp shown against the entry.
   */
  publishedAt: string;
  headline?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  media?: (number | null) | Media;
  author?: (number | null) | Author;
  /**
   * Pinned entries stay at the top of the timeline.
   */
  isPinned?: boolean | null;
  /**
   * Marks this entry as correcting an earlier one.
   */
  isCorrection?: boolean | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL segment. Leave blank to generate it from the title. Bengali characters are preserved.
   */
  slug: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Adds this page to the legal links row in the footer.
   */
  showInFooter?: boolean | null;
  /**
   * Leave blank to derive metadata from the content itself.
   */
  seo?: {
    /**
     * Overrides the page title. Around 60 characters renders best.
     */
    title?: string | null;
    /**
     * Overrides the meta description. Around 155 characters.
     */
    description?: string | null;
    /**
     * Overrides the Open Graph image. Falls back to the featured image.
     */
    image?: (number | null) | Media;
    /**
     * Absolute URL. Set this only when this page is a duplicate of a canonical page elsewhere.
     */
    canonicalUrl?: string | null;
    /**
     * Ask search engines not to index this page.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * Background work. Rows with an error have exhausted their retries and need attention.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'publish-scheduled' | 'expire-breaking' | 'revalidate' | 'search-index' | 'prune-jobs';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        parent?: {
          taskSlug?:
            ('inline' | 'publish-scheduled' | 'expire-breaking' | 'revalidate' | 'search-index' | 'prune-jobs') | null;
          taskID?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'publish-scheduled' | 'expire-breaking' | 'revalidate' | 'search-index' | 'prune-jobs') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  /**
   * Used for concurrency control. Jobs with the same key are subject to exclusive/supersedes rules.
   */
  concurrencyKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'live-blogs';
        value: number | LiveBlog;
      } | null)
    | ({
        relationTo: 'live-blog-updates';
        value: number | LiveBlogUpdate;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  headline?: T;
  subheadline?: T;
  slug?: T;
  summary?: T;
  body?: T;
  authors?: T;
  primaryCategory?: T;
  categories?: T;
  tags?: T;
  featuredImage?: T;
  articleType?: T;
  workflowStatus?: T;
  workflowNote?: T;
  workflowHistory?:
    | T
    | {
        from?: T;
        to?: T;
        at?: T;
        actor?: T;
        note?: T;
        id?: T;
      };
  publishedAt?: T;
  scheduledAt?: T;
  isBreaking?: T;
  breakingUntil?: T;
  isFeatured?: T;
  translationOf?: T;
  correction?:
    | T
    | {
        hasCorrection?: T;
        note?: T;
        correctedAt?: T;
      };
  createdBy?: T;
  lastEditedBy?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  parent?: T;
  image?: T;
  displayOrder?: T;
  isActive?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  displayName?: T;
  slug?: T;
  user?: T;
  avatar?: T;
  designation?: T;
  biography?: T;
  contact?:
    | T
    | {
        email?: T;
        website?: T;
        x?: T;
        facebook?: T;
        linkedin?: T;
      };
  isActive?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  copyright?: T;
  source?: T;
  mediaType?: T;
  usageRestrictions?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-blogs_select".
 */
export interface LiveBlogsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  status?: T;
  authors?: T;
  relatedArticle?: T;
  startedAt?: T;
  endedAt?: T;
  createdBy?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-blog-updates_select".
 */
export interface LiveBlogUpdatesSelect<T extends boolean = true> {
  liveBlog?: T;
  publishedAt?: T;
  headline?: T;
  content?: T;
  media?: T;
  author?: T;
  isPinned?: T;
  isCorrection?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  body?: T;
  showInFooter?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        parent?:
          | T
          | {
              taskSlug?: T;
              taskID?: T;
            };
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  concurrencyKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * The main story. Leave empty to use the most recent published article.
   */
  leadStory?: (number | null) | Article;
  /**
   * Up to four stories beside the lead.
   */
  secondaryLeads?: (number | Article)[] | null;
  latestNews?: {
    heading?: string | null;
    /**
     * How many recent stories to list.
     */
    limit?: number | null;
  };
  /**
   * Section blocks, in the order they should appear.
   */
  categorySections?:
    | {
        category: number | Category;
        heading?: string | null;
        limit?: number | null;
        id?: string | null;
      }[]
    | null;
  editorsPicks?: {
    heading?: string | null;
    articles?: (number | Article)[] | null;
  };
  trending?: {
    heading?: string | null;
    /**
     * Ordered by view count, which is eventually consistent — counts are aggregated periodically, not written per request.
     */
    enabled?: boolean | null;
    limit?: number | null;
  };
  mediaSection?: {
    heading?: string | null;
    enabled?: boolean | null;
    limit?: number | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Main masthead navigation. Ten entries maximum.
   */
  primary?:
    | {
        label: string;
        type: 'category' | 'page' | 'custom';
        category?: (number | null) | Category;
        page?: (number | null) | Page;
        url?: string | null;
        children?:
          | {
              label: string;
              type: 'category' | 'page' | 'custom';
              category?: (number | null) | Category;
              page?: (number | null) | Page;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Show the breaking-news ticker beneath the masthead.
   */
  showBreakingTicker?: boolean | null;
  tickerLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  columns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              type: 'category' | 'page' | 'custom';
              category?: (number | null) | Category;
              page?: (number | null) | Page;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown after the year, which is added automatically.
   */
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  logo?: (number | null) | Media;
  /**
   * Used for Organization structured data.
   */
  organization?: {
    legalName?: string | null;
    foundingDate?: string | null;
    /**
     * Wikipedia, Wikidata or official profiles.
     */
    sameAs?:
      | {
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
    /**
     * Tips and corrections address, shown on articles.
     */
    newsroomEmail?: string | null;
  };
  social?:
    | {
        platform: 'facebook' | 'x' | 'youtube' | 'instagram' | 'linkedin' | 'whatsapp';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults".
 */
export interface SeoDefault {
  id: number;
  /**
   * %s is replaced by the page title.
   */
  titleTemplate?: string | null;
  /**
   * Used for pages with no title of their own.
   */
  defaultTitle?: string | null;
  defaultDescription?: string | null;
  /**
   * Open Graph fallback. 1200×630 renders best.
   */
  defaultImage?: (number | null) | Media;
  /**
   * Including the @.
   */
  twitterHandle?: string | null;
  /**
   * Uncheck to add a site-wide noindex. Intended for staging environments only.
   */
  allowIndexing?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  leadStory?: T;
  secondaryLeads?: T;
  latestNews?:
    | T
    | {
        heading?: T;
        limit?: T;
      };
  categorySections?:
    | T
    | {
        category?: T;
        heading?: T;
        limit?: T;
        id?: T;
      };
  editorsPicks?:
    | T
    | {
        heading?: T;
        articles?: T;
      };
  trending?:
    | T
    | {
        heading?: T;
        enabled?: T;
        limit?: T;
      };
  mediaSection?:
    | T
    | {
        heading?: T;
        enabled?: T;
        limit?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  primary?:
    | T
    | {
        label?: T;
        type?: T;
        category?: T;
        page?: T;
        url?: T;
        children?:
          | T
          | {
              label?: T;
              type?: T;
              category?: T;
              page?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  showBreakingTicker?: T;
  tickerLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              type?: T;
              category?: T;
              page?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  organization?:
    | T
    | {
        legalName?: T;
        foundingDate?: T;
        sameAs?:
          | T
          | {
              url?: T;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
        newsroomEmail?: T;
      };
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults_select".
 */
export interface SeoDefaultsSelect<T extends boolean = true> {
  titleTemplate?: T;
  defaultTitle?: T;
  defaultDescription?: T;
  defaultImage?: T;
  twitterHandle?: T;
  allowIndexing?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskPublish-scheduled".
 */
export interface TaskPublishScheduled {
  input: {
    /**
     * Ties this job back to the request that queued it.
     */
    correlationId?: string | null;
  };
  output: {
    published?: number | null;
    failed?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskExpire-breaking".
 */
export interface TaskExpireBreaking {
  input: {
    /**
     * Ties this job back to the request that queued it.
     */
    correlationId?: string | null;
  };
  output: {
    cleared?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskRevalidate".
 */
export interface TaskRevalidate {
  input: {
    /**
     * Ties this job back to the request that queued it.
     */
    correlationId?: string | null;
    /**
     * The content change, as `RevalidationEvent`.
     */
    event:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output: {
    paths?: number | null;
    purged?: boolean | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSearch-index".
 */
export interface TaskSearchIndex {
  input: {
    /**
     * Ties this job back to the request that queued it.
     */
    correlationId?: string | null;
    collection: string;
    documentId: string;
  };
  output: {
    indexed?: number | null;
    removed?: boolean | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskPrune-jobs".
 */
export interface TaskPruneJobs {
  input: {
    /**
     * Ties this job back to the request that queued it.
     */
    correlationId?: string | null;
    /**
     * Retention window for completed jobs. Defaults to 7.
     */
    olderThanDays?: number | null;
  };
  output: {
    deleted?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}