import { can } from '@dhakalive/core'
import type { CollectionConfig, Where } from 'payload'

import { hasCapability, toAuthUser } from '../access'

/**
 * Uploaded media.
 *
 * Files live in Cloudflare R2 in every environment above development — the
 * storage adapter is attached in `payload.config.ts` when R2 is configured, and
 * environment validation refuses to start in production without it. Nothing is
 * ever written to a container's disk in production.
 */

/** Extensions are easy to spoof; the browser-declared MIME type is the gate. */
const ALLOWED_MIME_TYPES = [
  'image/jpeg',
  'image/png',
  'image/webp',
  'image/avif',
  'image/gif',
  'application/pdf',
  'video/mp4',
  'video/webm',
  'audio/mpeg',
  'audio/mp4',
]

const MAX_UPLOAD_BYTES = 50 * 1024 * 1024 // 50 MB

export const Media: CollectionConfig = {
  slug: 'media',

  access: {
    // Public read: media is served through the CDN and referenced by published
    // articles. Restricted assets are handled by `usageRestrictions` plus signed
    // URLs, not by hiding the row.
    read: () => true,
    create: hasCapability('media:upload'),
    update: ({ req }) => {
      const user = toAuthUser(req.user)
      if (!user) return false
      if (can(user, 'media:manage.any')) return true
      // Uploaders may correct their own metadata — alt text, credit, caption.
      return { uploadedBy: { equals: user.id } } satisfies Where
    },
    delete: hasCapability('media:manage.any'),
  },

  admin: {
    useAsTitle: 'filename',
    defaultColumns: ['filename', 'alt', 'mediaType', 'credit', 'updatedAt'],
    group: 'Content',
    description: 'Images, video and documents. Alt text is required for images.',
  },

  upload: {
    // Dev-only fallback; in production the S3/R2 adapter takes over and nothing
    // touches this path.
    staticDir: 'media',
    mimeTypes: ALLOWED_MIME_TYPES,
    /**
     * Responsive sizes generated by sharp. The originals are preserved
     * alongside them so an editor can always retrieve the untouched file.
     */
    imageSizes: [
      { name: 'thumbnail', width: 320, height: 240, position: 'centre' },
      { name: 'card', width: 640, withoutEnlargement: true },
      { name: 'feature', width: 1024, withoutEnlargement: true },
      { name: 'wide', width: 1600, withoutEnlargement: true },
      // 1200x630 is the Open Graph card ratio.
      { name: 'og', width: 1200, height: 630, position: 'centre' },
    ],
    focalPoint: true,
    crop: true,
    /**
     * Left false (the default) so sharp strips EXIF on resize. Camera metadata
     * routinely carries GPS coordinates, which for a news photograph can expose
     * a source's location.
     */
    withMetadata: false,
    adminThumbnail: 'thumbnail',
  },

  fields: [
    {
      name: 'alt',
      type: 'text',
      localized: true,
      admin: {
        description:
          'Describes the image for screen readers. Required for images; an image cannot be used as a featured image without it.',
      },
      validate: (value: unknown, { data }: { data?: Record<string, unknown> }) => {
        const mimeType = typeof data?.mimeType === 'string' ? data.mimeType : ''
        const isImage = mimeType.startsWith('image/')
        if (!isImage) return true
        if (typeof value === 'string' && value.trim().length > 0) return true
        return 'Alt text is required for images'
      },
    },
    {
      name: 'caption',
      type: 'textarea',
      localized: true,
      admin: { description: 'Shown beneath the image on the public site.' },
    },
    {
      name: 'credit',
      type: 'text',
      admin: { description: 'Photographer or agency, e.g. "Reuters / Jane Doe".' },
    },
    {
      name: 'copyright',
      type: 'text',
    },
    {
      name: 'source',
      type: 'text',
      admin: { description: 'Where the file came from — wire service, contributor, archive.' },
    },
    {
      name: 'mediaType',
      type: 'select',
      defaultValue: 'image',
      index: true,
      options: [
        { label: 'Image', value: 'image' },
        { label: 'Video', value: 'video' },
        { label: 'Audio', value: 'audio' },
        { label: 'Document', value: 'document' },
      ],
      admin: { description: 'Derived from the file on upload; override if needed.' },
    },
    {
      name: 'usageRestrictions',
      type: 'select',
      defaultValue: 'none',
      options: [
        { label: 'No restrictions', value: 'none' },
        { label: 'Editorial use only', value: 'editorial-only' },
        { label: 'One-time use', value: 'one-time' },
        { label: 'Internal — do not publish', value: 'internal' },
      ],
      admin: { description: 'Shown to editors before they place the asset in a story.' },
    },
    {
      name: 'uploadedBy',
      type: 'relationship',
      relationTo: 'users',
      index: true,
      admin: { readOnly: true, position: 'sidebar' },
      access: {
        // Provenance is a record, not an editable field.
        update: () => false,
      },
      hooks: {
        beforeChange: [
          ({ req, operation, value }): unknown => {
            if (operation !== 'create') return value
            return toAuthUser(req.user)?.id ?? value
          },
        ],
      },
    },
  ],

  hooks: {
    beforeValidate: [
      ({ data, req }) => {
        if (!data) return data

        /**
         * Reject oversized uploads before sharp is asked to process them.
         *
         * `data.filesize` is what Payload populates from the processed file and
         * is present on both the HTTP and Local API paths; `req.file` exists
         * only for HTTP requests, so checking it alone would leave programmatic
         * uploads — imports, migrations, seeds — unguarded.
         */
        const size = typeof data.filesize === 'number' ? data.filesize : req.file?.size
        if (typeof size === 'number' && size > MAX_UPLOAD_BYTES) {
          throw new Error(
            `File is larger than the ${Math.round(MAX_UPLOAD_BYTES / 1024 / 1024)} MB limit`,
          )
        }

        // Classify by the real MIME type rather than trusting the editor's pick.
        const mimeType = typeof data.mimeType === 'string' ? data.mimeType : req.file?.mimetype
        if (typeof mimeType === 'string') {
          if (mimeType.startsWith('image/')) data.mediaType = 'image'
          else if (mimeType.startsWith('video/')) data.mediaType = 'video'
          else if (mimeType.startsWith('audio/')) data.mediaType = 'audio'
          else data.mediaType = 'document'
        }

        return data
      },
    ],
  },

  timestamps: true,
}

export { ALLOWED_MIME_TYPES, MAX_UPLOAD_BYTES }
