import type { ImageInput } from '@dhakalive/core'

import type { Media } from '../payload-types'

/**
 * Reading URLs and dimensions off an upload relationship.
 *
 * Three places need this — structured data, the search index, Open Graph — and
 * each wants a different size. Keeping the size preference and the "is this
 * relationship even populated?" check in one place is what stops them drifting
 * into three subtly different ideas of which URL to use.
 */

/** Sizes generated by the Media collection, largest first. */
export type MediaSize = 'wide' | 'feature' | 'og' | 'card' | 'thumbnail'

function asMedia(value: unknown): Media | null {
  if (!value || typeof value !== 'object') return null
  const candidate = value as Media
  return typeof candidate.url === 'string' && candidate.url.length > 0 ? candidate : null
}

/**
 * Best URL for a purpose.
 *
 * Falls through the preferred sizes in order and then to the original. sharp
 * only generates a size when the source is large enough — `withoutEnlargement`
 * — so a small upload legitimately has no `wide`, and the fallback is not an
 * error path.
 */
export function mediaUrl(value: unknown, prefer: readonly MediaSize[] = []): string | null {
  const media = asMedia(value)
  if (!media) return null

  for (const size of prefer) {
    const url = media.sizes?.[size]?.url
    if (typeof url === 'string' && url.length > 0) return url
  }

  return media.url ?? null
}

/** URL plus intrinsic dimensions, which structured data wants together. */
export function mediaImage(value: unknown, prefer: readonly MediaSize[] = []): ImageInput | null {
  const media = asMedia(value)
  if (!media) return null

  for (const size of prefer) {
    const candidate = media.sizes?.[size]
    if (candidate?.url) {
      return {
        url: candidate.url,
        width: candidate.width ?? null,
        height: candidate.height ?? null,
      }
    }
  }

  return media.url
    ? { url: media.url, width: media.width ?? null, height: media.height ?? null }
    : null
}

/**
 * The image set for a news article.
 *
 * Google asks for multiple aspect ratios of the same image so it can choose one
 * per surface. These are crops of one upload, not different photographs, so
 * duplicates are removed rather than passed through.
 */
export function articleImages(value: unknown): ImageInput[] {
  const media = asMedia(value)
  if (!media) return []

  const candidates: (ImageInput | null)[] = [
    mediaImage(value, ['wide']),
    mediaImage(value, ['og']),
    mediaImage(value, ['card']),
  ]

  const seen = new Set<string>()
  const images: ImageInput[] = []

  for (const image of candidates) {
    if (!image || seen.has(image.url)) continue
    seen.add(image.url)
    images.push(image)
  }

  return images
}
